#!/usr/bin/env bash
# Usage: luaenv completions <command> [arg1 arg2...]

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  luaenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "luaenv-$COMMAND" || command -v "luaenv-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide luaenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
