#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: luaenv which <command>
#
# Displays the full path to the executable that luaenv will invoke when
# you run the given command.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  exec luaenv shims --short
fi

expand_path() {
  if [ ! -d "$1" ]; then
    return 1
  fi

  local cwd="$(pwd)"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  if [ -z "$path_to_remove" ]; then
    echo "${PATH}"
    return
  fi

  local paths
  IFS=: paths=($PATH)

  for path in "${paths[@]}"; do
    path="$(expand_path "$path" || true)"
    if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

LUAENV_VERSION="$(luaenv-version-name)"
LUAENV_COMMAND="$1"

if [ -z "$LUAENV_COMMAND" ]; then
  luaenv-help --usage which >&2
  exit 1
fi

if [ "$LUAENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${LUAENV_ROOT}/shims")"
  LUAENV_COMMAND_PATH="$(command -v "$LUAENV_COMMAND" || true)"
else
  LUAENV_COMMAND_PATH="${LUAENV_ROOT}/versions/${LUAENV_VERSION}/bin/${LUAENV_COMMAND}"
fi

for script in $(luaenv-hooks which); do
  source "$script"
done

if [ -x "$LUAENV_COMMAND_PATH" ]; then
  echo "$LUAENV_COMMAND_PATH"
else
  echo "luaenv: $LUAENV_COMMAND: command not found" >&2

  versions="$(luaenv-whence "$LUAENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Lua versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
