#!/usr/bin/env bash
# Summary: Explain how the current Lua version is set
set -e
[ -n "$LUAENV_DEBUG" ] && set -x

if [ -n "$LUAENV_VERSION" ]; then
  echo "LUAENV_VERSION environment variable"
else
  luaenv-version-file
fi
