#!/usr/bin/env bash
# Summary: Show the current Lua version
set -e
[ -n "$LUAENV_DEBUG" ] && set -x

if [ -z "$LUAENV_VERSION" ]; then
  LUAENV_VERSION_FILE="$(luaenv-version-file)"
  LUAENV_VERSION="$(luaenv-version-file-read "$LUAENV_VERSION_FILE" || true)"
fi

if [ -z "$LUAENV_VERSION" ] || [ "$LUAENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${LUAENV_ROOT}/versions/${version}" ]
}

if version_exists "$LUAENV_VERSION"; then
  echo "$LUAENV_VERSION"
elif version_exists "${LUAENV_VERSION#lua-}"; then
  { echo "warning: ignoring extraneous \`lua-' prefix in version \`${LUAENV_VERSION}'"
    echo "         (set by $(luaenv-version-origin))"
  } >&2
  echo "${LUAENV_VERSION#lua-}"
else
  echo "luaenv: version \`$LUAENV_VERSION' is not installed" >&2
  exit 1
fi
