#!/usr/bin/env bash
set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  exec luaenv-rehash --complete
fi

# When luaenv shell integration is enabled, delegate to luaenv-rehash,
# then tell the shell to empty its command lookup cache.
luaenv-rehash
echo "hash -r 2>/dev/null || true"
