#!/usr/bin/env bash
# Summary: List existing luaenv shims
# Usage: luaenv shims [--short]

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

for command in "${LUAENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
