#!/usr/bin/env bash
# Summary: Configure the shell environment for luaenv
# Usage: eval "$(luaenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="$(basename "${shell:-$SHELL}")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "luaenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load luaenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and . (luaenv init -|psub)'
      ;;
    * )
      echo 'eval "$(luaenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${LUAENV_ROOT}/"{shims,versions}

if [[ ":${PATH}:" != *:"${LUAENV_ROOT}/shims":* ]]; then
  case "$shell" in
  fish )
    echo "setenv PATH '${LUAENV_ROOT}/shims' \$PATH"
  ;;
  * )
    echo 'export PATH="'${LUAENV_ROOT}'/shims:${PATH}"'
  ;;
  esac
fi

case "$shell" in
fish )
  echo "setenv LUAENV_SHELL $shell"
;;
* )
  echo "export LUAENV_SHELL=$shell"
;;
esac

completion="${root}/completions/luaenv.${shell}"
if [ -r "$completion" ]; then
  case "$shell" in
  fish ) echo ". '$completion'" ;;
  *    ) echo "source '$completion'" ;;
  esac
fi

if [ -z "$no_rehash" ]; then
  echo 'luaenv rehash 2>/dev/null'
fi

commands=(`luaenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function luaenv
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    eval (luaenv "sh-\$command" \$argv)
  case '*'
    command luaenv "\$command" \$argv
  end
end
EOS
  exit 0
  ;;
ksh )
  cat <<EOS
function luaenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
luaenv() {
  local command
EOS
  ;;
esac

IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\`luaenv "sh-\$command" "\$@"\`";;
  *)
    command luaenv "\$command" "\$@";;
  esac
}
EOS
