#!/usr/bin/env bash
# Summary: Detect the file that sets the current luaenv version
set -e
[ -n "$LUAENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.lua-version" ]; then
      echo "${root}/.lua-version"
      exit
    elif [ -e "${root}/.luaenv-version" ]; then
      echo "${root}/.luaenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$LUAENV_DIR"
[ "$LUAENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${LUAENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${LUAENV_ROOT}/global" ]; then
  echo "${LUAENV_ROOT}/global"
elif [ -e "${LUAENV_ROOT}/default" ]; then
  echo "${LUAENV_ROOT}/default"
else
  echo "$global_version_file"
fi
