#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: luaenv which <command>
#
# Displays the full path to the executable that luaenv will invoke when
# you run the given command.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  exec luaenv-shims --short
fi

remove_from_path() {
  local path_to_remove="$1"
  local path_before
  local result=":$PATH:"
  while [ "$path_before" != "$result" ]; do
    path_before="$result"
    result="${result//:$path_to_remove:/:}"
  done
  echo "${result%:}"
}

LUAENV_COMMAND="$1"

if [ -z "$LUAENV_COMMAND" ]; then
  luaenv-help --usage which >&2
  exit 1
fi

LUAENV_VERSION="${LUAENV_VERSION:-$(luaenv-version-name)}"

if [ "$LUAENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${LUAENV_ROOT}/shims")"
  LUAENV_COMMAND_PATH="$(command -v "$LUAENV_COMMAND" || true)"
else
  LUAENV_COMMAND_PATH="${LUAENV_ROOT}/versions/${LUAENV_VERSION}/bin/${LUAENV_COMMAND}"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`luaenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$LUAENV_COMMAND_PATH" ]; then
  echo "$LUAENV_COMMAND_PATH"
elif ! [ -d "${LUAENV_ROOT}/versions/${LUAENV_VERSION}" ]; then
  echo "luaenv: version \`$LUAENV_VERSION' is not installed" >&2
  exit 1
else
  echo "luaenv: $LUAENV_COMMAND: command not found" >&2

  versions="$(luaenv-whence "$LUAENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Lua versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
