#!/usr/bin/env bash
# Summary: List all Lua versions available to luaenv
# Usage: luaenv versions [--bare]
#
# Lists all Lua versions found in `$LUAENV_ROOT/versions/*'.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(luaenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(luaenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && LUAENV_VERSION=system luaenv-which lua >/dev/null 2>&1; then
  print_version system
fi

for path in "${LUAENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
