#!/usr/bin/env bash
# Summary: List hook scripts for a given luaenv command
# Usage: luaenv hooks <command>

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

LUAENV_COMMAND="$1"
if [ -z "$LUAENV_COMMAND" ]; then
  luaenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/luaenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$LUAENV_NATIVE_EXT" ]; then
    echo "luaenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "luaenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($LUAENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$LUAENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
