#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Lua version
#
# Usage: luaenv shell <version>
#        luaenv shell --unset
#
# Sets a shell-specific Lua version by setting the `LUAENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Lua version known to luaenv.
# The special version string `system' will use your default system Lua.
# Run `luaenv versions' for a list of available Lua versions.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec luaenv-versions --bare
fi

version="$1"
shell="$(basename "${LUAENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$LUAENV_VERSION" ]; then
    echo "luaenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$LUAENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e LUAENV_VERSION"
    ;;
  * )
    echo "unset LUAENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if luaenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv LUAENV_VERSION \"${version}\""
    ;;
  * )
    echo "export LUAENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
