#!/usr/bin/env bash
# Usage: luaenv version-file-write <file> <version>

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

LUAENV_VERSION_FILE="$1"
LUAENV_VERSION="$2"

if [ -z "$LUAENV_VERSION" ] || [ -z "$LUAENV_VERSION_FILE" ]; then
  luaenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
luaenv-prefix "$LUAENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$LUAENV_VERSION" > "$LUAENV_VERSION_FILE"
