#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Lua version
#
# Usage: luaenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Lua
# version's `bin' directory is at the front.
#
# For example, if the currently selected Lua version is 5.2.1:
#   luaenv exec bundle install
#
# is equivalent to:
#   PATH="$LUAENV_ROOT/versions/5.2.1/bin:$PATH" bundle install

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  exec luaenv shims --short
fi

LUAENV_VERSION="$(luaenv-version-name)"
LUAENV_COMMAND="$1"

if [ -z "$LUAENV_COMMAND" ]; then
  luaenv-help --usage exec >&2
  exit 1
fi

export LUAENV_VERSION
LUAENV_COMMAND_PATH="$(luaenv-which "$LUAENV_COMMAND")"
LUAENV_BIN_PATH="${LUAENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`luaenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$LUAENV_VERSION" != "system" ]; then
  export PATH="${LUAENV_BIN_PATH}:${PATH}"
fi
exec -a "$LUAENV_COMMAND" "$LUAENV_COMMAND_PATH" "$@"
