#!/usr/bin/env bash
# Summary: Show the current Lua version and its origin
#
# Shows the currently selected Lua version and how it was
# selected. To obtain only the version string, use `luaenv
# version-name'.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

echo "$(luaenv-version-name) (set by $(luaenv-version-origin))"
