#!/usr/bin/env bash
# Summary: Display prefix for a Lua version
# Usage: luaenv prefix [<version>]
#
# Displays the directory where a Lua version is installed. If no
# version is given, `luaenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec luaenv-versions --bare
fi

if [ -n "$1" ]; then
  export LUAENV_VERSION="$1"
elif [ -z "$LUAENV_VERSION" ]; then
  LUAENV_VERSION="$(luaenv-version-name)"
fi

if [ "$LUAENV_VERSION" = "system" ]; then
  if LUA_PATH="$(luaenv-which lua 2>/dev/null)"; then
    LUA_PATH="${LUA_PATH%/*}"
    echo "${LUA_PATH%/bin}"
    exit
  else
    echo "luaenv: system version not found in PATH" >&2
    exit 1
  fi
fi

LUAENV_PREFIX_PATH="${LUAENV_ROOT}/versions/${LUAENV_VERSION}"
if [ ! -d "$LUAENV_PREFIX_PATH" ]; then
  echo "luaenv: version \`${LUAENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$LUAENV_PREFIX_PATH"
