#!/usr/bin/env bash
#
# Summary: Set or show the global Lua version
#
# Usage: luaenv global <version>
#
# Sets the global Lua version. You can override the global version at
# any time by setting a directory-specific version with `luaenv local'
# or by setting the `LUAENV_VERSION' environment variable.
#
# <version> should be a string matching a Lua version known to luaenv.
# The special version string `system' will use your default system Lua.
# Run `luaenv versions' for a list of available Lua versions.

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec luaenv-versions --bare
fi

LUAENV_VERSION="$1"
LUAENV_VERSION_FILE="${LUAENV_ROOT}/version"

if [ -n "$LUAENV_VERSION" ]; then
  luaenv-version-file-write "$LUAENV_VERSION_FILE" "$LUAENV_VERSION"
else
  luaenv-version-file-read "$LUAENV_VERSION_FILE" ||
  luaenv-version-file-read "${LUAENV_ROOT}/global" ||
  luaenv-version-file-read "${LUAENV_ROOT}/default" ||
  echo system
fi
