#!/usr/bin/env bash
# Summary: List all Lua versions that contain the given executable
# Usage: luaenv whence [--path] <command>

set -e
[ -n "$LUAENV_DEBUG" ] && set -x

# Provide luaenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec luaenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  luaenv-versions --bare | while read version; do
    path="$(luaenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

LUAENV_COMMAND="$1"
if [ -z "$LUAENV_COMMAND" ]; then
  luaenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$LUAENV_COMMAND")"
[ -n "$result" ] && echo "$result"
